FROM nginx:1.18.0

LABEL maintainer="https://annict.jp/@shimbaco" \
  description="A platform for anime addicts."

RUN apt update && \
  apt install -y \
  vim

COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
